
Description: Provisions a Lambda Error alarm

Resources:

  LambdaCriticalErrorAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      ActionsEnabled: true
      AlarmDescription: 'Error Alarm for Lambdas'
      AlarmName: 'Lambda Error Alarm'
      AlarmActions:
        - arn:aws:sns:us-east-1:042309865848:Alert
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      OKActions:
        - arn:aws:sns:us-east-1:042309865848:Alert


